version: '3.8'
services:
    server:
        container_name: moco-api
        build: '.'
        volumes:
            - ./:/node-app
            - ./node_modules:/node-app/node_modules
        ports:
            - '3001:3001'