version: '3'

services:
    db-postgres:
        image: 'postgres'
        restart: always
        container_name: db_postgres
        environment:
            POSTGRES_DB: 'moco'
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'root'
        ports:
            - '5432:5432'
        networks:
            moco-networks:
                ipv4_address: 173.28.1.1
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

    db-pgadmin:
        image: 'dpage/pgadmin4'
        restart: always
        container_name: db_pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'user@email.com'
            PGADMIN_DEFAULT_PASSWORD: 'user'
        ports:
            - '5433:80'
        depends_on:
            - db-postgres
        networks:
            moco-networks:
                ipv4_address: 173.28.1.2
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

    server:
        container_name: moco_api
        restart: always
        build: '.'
        command: bash -c "npm run migrate:apply && npm start"
        volumes:
            - ./:/node-app
            - ./node_modules:/node-app/node_modules
        env_file: src/enviroments/.env
        environment:
            NODE_ENV: development
            DB_HOST: 173.28.1.1
            DB_PORT: 5432
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: moco
        depends_on:
            - db-postgres
        links:
            - db-postgres
        ports:
            - '3001:3001'   
        networks:   
            moco-networks:
                ipv4_address: 173.28.1.3

networks: 
    moco-networks:
        ipam:
            driver: default
            config:
                - subnet: 173.28.0.0/16

volumes:
    moco-docker-data:
        driver: local 